name: syphon
description: a privacy focused matrix client

# flutter commands
# $ flutter create --org org.tether.tether
# $ flutter run --no-fast-start
# $ flutter run --no-sound-null-safety
# $ flutter pub get
# $ flutter pub upgrade --major-versions
# $ flutter pub global run devtools
# $ flutter pub run build_runner build
# $ flutter pub run build_runner watch --delete-conflicting-outputs
# $ flutter pub run build_runner build --delete-conflicting-outputs
# $ adb shell && pm uninstall org.tether.tether (sometimes doesn't uninstall when debugging?)

# troubleshooting
# $ pub cache repair
# $ flutter pub cache repair

# mobile development commands
# $ xcrun simctl delete unavailable
# $ xcrun simctl list devices
# $ xcrun simctl boot <device-id>
# $ xcrun simctl boot 9EC4AC8E-5BD0-4D38-A8FC-52504C130844
# $ emulator -list-avds
# $ emulator -avd Pixel_3a_API_29
# $ adb shell && run-as org.tether.tether # cache inspection
# $ adb logcat ActivityManager:I flutter:I *:S

# desktop support options
# $ flutter config --enable-macos-desktop
# $ flutter config --enable-linux-desktop
# $ flutter config --no-enable-<type>-desktop

# asset generation
# iOS icons - https://github.com/smallmuou/ios-icon-generator
#           - run generation script for ios and macos (desktop and mobile)
# android icons - use Android Studio with generic png

# env setup
# - git submodule update --init --recursive
# - defaults delete com.apple.dt.Xcode # Reset XCode settings
# - synctl start on 192.168.1.2 or respective local server
# - curl -XGET "http://192.168.1.2:8008/_matrix/client/r0/login" to test

# notes
# https://github.com/flutter/plugins/pull/1570

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 0.1.8+180

environment:
  sdk: ">=2.9.0 <3.0.0" # <- modified to solve build_runner

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state
  expandable: ^5.0.1
  equatable: ^2.0.0
  canonical_json: 1.0.0
  convert: ^3.0.0
  device_info: ^2.0.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  flutter_redux: ^0.8.2
  mime: ^1.0.0
  path_provider: ^2.0.1
  package_info: ^2.0.0

  # encryption
  olm: ^2.0.0
  crypt: ^4.0.1
  crypto: ^3.0.1
  encrypt: ^5.0.0

  # cache/storage
  sembast: ^3.0.1
  sqflite: ^2.0.0+3
  sqlite3: ^1.0.0
  sqlite3_flutter_libs: ^0.4.1
  sembast_sqflite: ^2.0.0+1
  sqflite_common_ffi: ^2.0.0
  # checked_yaml: ^2.0.1
  json_annotation: ^4.0.0
  flutter_secure_storage: ^4.1.0
  # sqflite_sqlcipher: 1.1.2

  # services
  http: ^0.13.1
  html: ^0.15.0
  intl: ^0.17.0
  http_parser: ^4.0.0
  easy_localization: ^3.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  android_alarm_manager: ^2.0.0
  uni_links: ^0.5.0
  # flutter_apns: 1.1.0  # TODO: extract only the iOS code and remove

  # Desktop UI Only - UNCOMMENT FOR BUILDS
  # window_utils: 1.0.2

  # UI Only
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  flutter_svg: ^0.22.0
  file_picker: ^3.0.1
  image_picker: ^0.7.4
  flutter_swiper: 1.1.6
  webview_flutter: ^2.0.4
  touchable_opacity: ^1.2.0
  fab_circular_menu: ^1.0.2
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_local_notifications: ^5.0.0+1
  flutter_material_color_picker: ^1.0.5
  palette_generator: ^0.3.0
  emoji_picker_flutter: ^1.0.3
  swipeable: 1.1.0

dev_dependencies:
  json_serializable: ^4.0.0
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.1

# dependency_overrides:
# intl: ^0.17.0-nullsafety.2 # <-- override for desktop builds on dev channel

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/current/app_icon_ios.png"
  adaptive_icon_background: "#34C7B5"
  adaptive_icon_foreground: "assets/icons/current/app_icon_foreground.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Light.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Light.ttf

  # To add assets to your application, add an assets section, like this:
  # On release, change .env.debug to .env
  assets:
    - ./.env.debug
    - ./.env.release
    - assets/translations/en.json
    - assets/translations/ru.json
    - assets/graphics/undraw_sync_files.svg
    - assets/graphics/undraw_accept_terms.svg
    - assets/graphics/undraw_mobile_user.svg
    - assets/graphics/undraw_messaging_fun.svg
    - assets/graphics/undraw_connection.svg
    - assets/graphics/undraw_group_chat.svg
    - assets/graphics/undraw_people.svg
    - assets/graphics/undraw_site_content.svg
    - assets/graphics/undraw_escaping.svg
    - assets/graphics/undraw_message_sent.svg
    - assets/graphics/undraw_new_message.svg
    - assets/graphics/undraw_mail_sent.svg

    - assets/graphics/undraw_in_thought.svg
    - assets/graphics/undraw_profile_data.svg
    - assets/graphics/undraw_mention.svg
    - assets/graphics/undraw_not_found.svg
    - assets/icons/current/app_icon_cyan.svg
    - assets/icons/current/app_icon_cyan.png
    - assets/icons/current/app_icon_white.png
    - assets/icons/global/being-check.svg
    - assets/icons/global/being-person-add.svg
    - assets/icons/global/being-group-add.svg
    - assets/icons/global/being-public-add.svg
    - assets/icons/global/being-search-public.svg
    - assets/icons/global/being-search-public-condensed.svg
    - assets/icons/global/being-message-syphon.svg
    - assets/icons/global/being-send.svg
    - assets/icons/global/being-send-solid.svg
    - assets/icons/global/being-send-lock.svg
    - assets/icons/global/being-send-lock-solid.svg
    - assets/icons/global/being-send-unlock.svg
    - assets/icons/global/being-chevrons-right.svg
    - assets/icons/global/feather-message-circle.svg
